project_id = "dsaqlgxajdnwoqvtsrqd"

[functions.generate-script]
verify_jwt = true

[functions.generate-audio]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.create-guide]
verify_jwt = true