-- Insert sample audio guides with random creator IDs (bypassing foreign key constraints for demo purposes)
INSERT INTO public.audio_guides (id, title, description, location, category, difficulty, languages, price_usd, currency, creator_id, is_approved, is_published, duration, rating, total_reviews, total_purchases, image_url, audio_url, transcript, preview_url, best_time, created_at, updated_at) VALUES

-- Published guides
('750e8400-e29b-41d4-a716-446655440001', 'Vatican Museums & Sistine Chapel: Masterpieces Unveiled', 'Journey through centuries of artistic genius in this comprehensive guide to the Vatican Museums. Discover hidden details in Michelangelo''s Sistine Chapel ceiling, Raphael''s rooms, and countless masterpieces with insider knowledge from a Renaissance art specialist.', 'Vatican City, Rome', 'art', 'intermediate', ARRAY['english', 'italian'], 1299, 'usd', gen_random_uuid(), true, true, 4800, 4.8, 127, 89, 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop', 'https://example.com/audio/vatican-guide.mp3', 'Welcome to the Vatican Museums, home to one of the world''s greatest art collections...', 'https://example.com/preview/vatican-preview.mp3', 'Early morning (8-10 AM) for smaller crowds', now() - interval '25 days', now() - interval '20 days'),

('750e8400-e29b-41d4-a716-446655440002', 'Shibuya to Senso-ji: Modern Tokyo Meets Ancient Traditions', 'Experience the fascinating contrast between ultra-modern Shibuya and the ancient Senso-ji Temple. This guide takes you through Tokyo''s evolution from a fishing village to a global metropolis, with stops at hidden shrines and local eateries.', 'Tokyo, Japan', 'culture', 'beginner', ARRAY['english', 'japanese'], 999, 'usd', gen_random_uuid(), true, true, 3600, 4.9, 203, 156, 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop', 'https://example.com/audio/tokyo-guide.mp3', 'Konnichiwa! Welcome to Tokyo, where ancient traditions blend seamlessly with cutting-edge technology...', 'https://example.com/preview/tokyo-preview.mp3', 'Late afternoon to evening for the best experience', now() - interval '40 days', now() - interval '35 days'),

('750e8400-e29b-41d4-a716-446655440003', 'Machu Picchu: Lost City of the Incas', 'Uncover the mysteries of Machu Picchu with an expert archaeologist. Learn about Inca engineering marvels, astronomical alignments, and recent discoveries that continue to reshape our understanding of this UNESCO World Heritage site.', 'Machu Picchu, Peru', 'history', 'intermediate', ARRAY['english', 'spanish'], 1499, 'usd', gen_random_uuid(), true, true, 5400, 4.7, 94, 67, 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&h=600&fit=crop', 'https://example.com/audio/machu-picchu-guide.mp3', 'High in the Andes Mountains, shrouded in mist and mystery, lies Machu Picchu...', 'https://example.com/preview/machu-picchu-preview.mp3', 'Early morning (6-8 AM) for sunrise views', now() - interval '50 days', now() - interval '45 days'),

-- Approved but not yet published
('750e8400-e29b-41d4-a716-446655440004', 'Colosseum: Gladiators and Glory', 'Step into the arena where gladiators once fought for their lives. This immersive guide reveals the engineering genius behind Rome''s greatest amphitheater and the brutal spectacles that captivated an empire.', 'Rome, Italy', 'history', 'beginner', ARRAY['english', 'italian'], 899, 'usd', gen_random_uuid(), true, false, 2700, 0, 0, 0, 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop', 'https://example.com/audio/colosseum-guide.mp3', 'Welcome to the Colosseum, the largest amphitheater ever built...', 'https://example.com/preview/colosseum-preview.mp3', 'Early morning or late afternoon', now() - interval '10 days', now() - interval '8 days'),

-- Pending approval
('750e8400-e29b-41d4-a716-446655440005', 'Kyoto Temple Walk: Zen Gardens and Golden Pavilions', 'Discover the spiritual heart of Japan through Kyoto''s most magnificent temples. From the golden Kinkaku-ji to the thousand torii gates of Fushimi Inari, experience the serenity and beauty of Japanese Buddhist architecture.', 'Kyoto, Japan', 'culture', 'beginner', ARRAY['english', 'japanese'], 1199, 'usd', gen_random_uuid(), false, false, 4200, 0, 0, 0, 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&h=600&fit=crop', 'https://example.com/audio/kyoto-guide.mp3', 'Welcome to Kyoto, the ancient capital of Japan and home to over 2,000 temples...', 'https://example.com/preview/kyoto-preview.mp3', 'Early morning for peaceful temple visits', now() - interval '5 days', now() - interval '3 days'),

('750e8400-e29b-41d4-a716-446655440006', 'Santorini Sunset: Volcanic Beauty and Cycladic Culture', 'Experience the magic of Santorini beyond the Instagram photos. Learn about volcanic geology, traditional architecture, and local wine culture while watching the world''s most famous sunset from Oia.', 'Santorini, Greece', 'nature', 'easy', ARRAY['english', 'greek'], 799, 'usd', gen_random_uuid(), false, false, 2400, 0, 0, 0, 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&h=600&fit=crop', 'https://example.com/audio/santorini-guide.mp3', 'Welcome to Santorini, where volcanic forces created one of the world''s most beautiful islands...', 'https://example.com/preview/santorini-preview.mp3', 'Late afternoon for sunset viewing', now() - interval '2 days', now() - interval '1 day'),

-- Additional published guides
('750e8400-e29b-41d4-a716-446655440007', 'Louvre Museum: From Mona Lisa to Hidden Masterpieces', 'Navigate the world''s largest art museum with expert guidance. Skip the crowds and discover not just the famous Mona Lisa, but also hidden gems that most visitors miss in this treasure trove of human creativity.', 'Paris, France', 'art', 'intermediate', ARRAY['english', 'french'], 1099, 'usd', gen_random_uuid(), true, true, 4200, 4.6, 84, 63, 'https://images.unsplash.com/photo-1566139826633-d9d2b4b29b32?w=800&h=600&fit=crop', 'https://example.com/audio/louvre-guide.mp3', 'Bienvenue to the Louvre, where centuries of human artistic achievement await...', 'https://example.com/preview/louvre-preview.mp3', 'Early morning or late afternoon to avoid crowds', now() - interval '35 days', now() - interval '30 days'),

('750e8400-e29b-41d4-a716-446655440008', 'Cappadocia Hot Air Balloon: Fairy Chimneys from Above', 'Experience the magical landscape of Cappadocia from a unique perspective. Learn about the geological forces that created this wonder and the rich history of underground cities and ancient civilizations.', 'Cappadocia, Turkey', 'nature', 'easy', ARRAY['english', 'turkish'], 899, 'usd', gen_random_uuid(), true, true, 2400, 4.9, 156, 112, 'https://images.unsplash.com/photo-1539650116574-75c0c6d73ab2?w=800&h=600&fit=crop', 'https://example.com/audio/cappadocia-guide.mp3', 'Welcome to Cappadocia, where fairy chimneys rise like ancient skyscrapers...', 'https://example.com/preview/cappadocia-preview.mp3', 'Early morning for balloon flights', now() - interval '20 days', now() - interval '15 days');

-- Insert sample verification requests (these will have user_ids that don't correspond to actual users)
INSERT INTO public.verification_requests (id, user_id, full_name, experience_description, portfolio_url, social_media_links, status, submitted_at, reviewed_at, reviewed_by, admin_notes) VALUES
-- Pending requests
('650e8400-e29b-41d4-a716-446655440001', gen_random_uuid(), 'David Thompson', 'Professional photographer and travel writer with 5 years of experience creating visual stories about European destinations. Specialized in architectural photography and cultural documentation.', 'https://davidthompsonphoto.com', '{"instagram": "https://instagram.com/davidphoto", "website": "https://davidthompsonphoto.com"}', 'pending', now() - interval '3 days', null, null, null),

('650e8400-e29b-41d4-a716-446655440002', gen_random_uuid(), 'Amara Okafor', 'Licensed tour guide in Lagos and Abuja with expertise in Nigerian history and contemporary culture. Fluent in English, Yoruba, and Igbo.', 'https://amaraguides.ng', '{"linkedin": "https://linkedin.com/in/amara-okafor", "facebook": "https://facebook.com/amaraguides"}', 'pending', now() - interval '1 day', null, null, null),

-- Approved request 
('650e8400-e29b-41d4-a716-446655440003', gen_random_uuid(), 'Marco Rossi', 'Professional tour guide specializing in Italian Renaissance art and architecture. 15 years of experience guiding visitors through Rome and Florence.', 'https://marcorossi-guides.it', '{"website": "https://marcorossi-guides.it", "tripadvisor": "https://tripadvisor.com/marco-rossi"}', 'approved', now() - interval '35 days', now() - interval '30 days', gen_random_uuid(), 'Excellent credentials and portfolio. Approved for creator status.'),

-- Rejected request
('650e8400-e29b-41d4-a716-446655440004', gen_random_uuid(), 'John Smith', 'Travel blogger with 1 year of experience', null, '{"instagram": "https://instagram.com/johntravel"}', 'rejected', now() - interval '20 days', now() - interval '18 days', gen_random_uuid(), 'Insufficient professional experience. Please reapply after gaining more credentials in the travel industry.');