-- Insert demo creator profiles with verification and tier data
INSERT INTO public.profiles (user_id, email, full_name, bio, avatar_url, role, verification_status, verified_at, creator_badge, specialties, guide_country, experience_years, languages_spoken, current_tier, tier_points, social_profiles) VALUES
-- Marco Romano (Bronze, Italy)
('11111111-1111-1111-1111-111111111111', 'marco.romano@email.com', 'Marco Romano', 'Passionate archaeological guide specializing in ancient Roman history and UNESCO heritage sites. Join me for immersive journeys through time in the Eternal City.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '3 months', true, ARRAY['Archaeological Sites', 'Cultural Heritage', 'Roman History'], 'Italy', 2, ARRAY['Italian', 'English'], 'bronze', 150, '{"instagram": "marco_rome_guide", "website": "www.romewithamarco.com"}'),

-- Sakura Tanaka (Silver, Japan)
('22222222-2222-2222-2222-222222222222', 'sakura.tanaka@email.com', 'Sakura Tanaka', 'Traditional Japanese culture expert and temple guide. I share the spiritual beauty and historical depth of Kyoto through authentic cultural experiences.', 'https://images.unsplash.com/photo-1494790108755-2616b612b632?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '8 months', true, ARRAY['Cultural Heritage', 'Temples', 'Traditional Arts'], 'Japan', 5, ARRAY['Japanese', 'English', 'Mandarin'], 'silver', 420, '{"instagram": "sakura_kyoto", "facebook": "KyotoWithSakura"}'),

-- Ahmed Hassan (Gold, Egypt)
('33333333-3333-3333-3333-333333333333', 'ahmed.hassan@email.com', 'Ahmed Hassan', 'Egyptologist and UNESCO World Heritage specialist with extensive knowledge of ancient civilizations. Discover the mysteries of Egypt with expert archaeological insights.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '1 year', true, ARRAY['Archaeological Sites', 'UNESCO Heritage', 'Ancient Civilizations'], 'Egypt', 8, ARRAY['Arabic', 'English', 'French'], 'gold', 780, '{"linkedin": "ahmed-hassan-egyptologist", "website": "www.egyptwitahahmed.com"}'),

-- Elena Vasquez (Diamond, Spain)
('44444444-4444-4444-4444-444444444444', 'elena.vasquez@email.com', 'Elena Vasquez', 'Art historian and museum curator specializing in Renaissance and modern art. Experience world-class museums and galleries through the eyes of an expert.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '2 years', true, ARRAY['Art & Museums', 'Renaissance Art', 'Cultural Heritage'], 'Spain', 12, ARRAY['Spanish', 'English', 'French', 'Italian'], 'diamond', 1200, '{"linkedin": "elena-vasquez-art", "instagram": "elena_art_madrid"}'),

-- James Fletcher (Gold, UK)
('55555555-5555-5555-5555-555555555555', 'james.fletcher@email.com', 'James Fletcher', 'British history enthusiast and castle specialist. Explore centuries of history through medieval castles, royal palaces, and historic battlefields across the UK.', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '10 months', true, ARRAY['Historical Sites', 'Medieval History', 'Castles'], 'United Kingdom', 7, ARRAY['English'], 'gold', 690, '{"instagram": "james_uk_history", "website": "www.britishheritage.tours"}'),

-- Lisa Chen (Silver, Singapore)
('66666666-6666-6666-6666-666666666666', 'lisa.chen@email.com', 'Lisa Chen', 'Cultural influencer and food heritage guide. Discover Singapore diverse culinary landscape and multicultural heritage through authentic local experiences.', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '6 months', true, ARRAY['Food Culture', 'Multicultural Heritage', 'Urban Exploration'], 'Singapore', 4, ARRAY['English', 'Mandarin', 'Malay'], 'silver', 380, '{"instagram": "lisa_sg_eats", "tiktok": "lisa_singapore", "youtube": "Lisa Chen Singapore"}'),

-- Carlos Mendoza (Bronze, Mexico)
('77777777-7777-7777-7777-777777777777', 'carlos.mendoza@email.com', 'Carlos Mendoza', 'Adventure guide and nature enthusiast exploring Mexico natural wonders. From ancient cenotes to volcanic landscapes, discover the country incredible biodiversity.', 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '1 month', true, ARRAY['Natural Wonders', 'Adventure Tourism', 'Ecology'], 'Mexico', 1, ARRAY['Spanish', 'English'], 'bronze', 85, '{"instagram": "carlos_mexico_nature"}'),

-- Priya Sharma (Gold, India)
('88888888-8888-8888-8888-888888888888', 'priya.sharma@email.com', 'Priya Sharma', 'UNESCO World Heritage expert and cultural anthropologist. Experience India rich spiritual and architectural heritage through immersive storytelling and local wisdom.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face', 'content_creator', 'verified', now() - interval '15 months', true, ARRAY['UNESCO Heritage', 'Spiritual Tourism', 'Architecture'], 'India', 9, ARRAY['Hindi', 'English', 'Bengali'], 'gold', 850, '{"instagram": "priya_india_heritage", "website": "www.indiaheritage.guide"}');