-- Insert demo creator profiles with demo IDs that match the CreatorProfile component
INSERT INTO public.profiles (
  id, user_id, email, full_name, role, verification_status, creator_badge, 
  bio, specialties, languages_spoken, experience_years, current_tier, tier_points,
  avatar_url, social_profiles, guide_country, created_at, updated_at
) VALUES 
(
  'demo-elena-id',
  'demo-elena-user',
  'elena@demoguides.com',
  'Elena Rossi',
  'content_creator',
  'verified',
  true,
  'Art historian specializing in Renaissance masterpieces and hidden gems of Italian culture. I''ve been guiding visitors through Italy''s greatest museums and secret locations for over 10 years.',
  ARRAY['Art History', 'Museums', 'Renaissance', 'Italian Culture'],
  ARRAY['English', 'Italian', 'French'],
  10,
  'gold',
  850,
  'https://images.unsplash.com/photo-1494790108755-2616c819e3f5?w=400&h=400&fit=crop&crop=face',
  '{"instagram": "@elena_artguide", "website": "www.elenarossi.guide"}',
  'Italy',
  now() - interval '2 years',
  now()
),
(
  'demo-kenji-id',
  'demo-kenji-user',
  'kenji@demoguides.com',
  'Kenji Tanaka',
  'content_creator',
  'verified',
  true,
  'Local Kyoto guide and cultural expert passionate about sharing traditional Japanese culture, temples, and the hidden stories behind ancient traditions.',
  ARRAY['Japanese Culture', 'Temples', 'Traditional Arts', 'Local History'],
  ARRAY['English', 'Japanese'],
  8,
  'gold',
  720,
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
  '{"twitter": "@kenji_kyoto", "instagram": "@kyoto_cultural_walks"}',
  'Japan',
  now() - interval '18 months',
  now()
),
(
  'demo-maria-id',
  'demo-maria-user',
  'maria@demoguides.com',
  'Dr. Maria Garcia',
  'content_creator',
  'verified',
  true,
  'Archaeologist and cultural historian specializing in Mayan civilization and ancient Mesoamerican cultures. Leading expert on Chichen Itza and surrounding archaeological sites.',
  ARRAY['Archaeology', 'Mayan History', 'Ancient Civilizations', 'Cultural Heritage'],
  ARRAY['English', 'Spanish', 'Portuguese'],
  15,
  'platinum',
  1200,
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
  '{"linkedin": "dr-maria-garcia-archaeology", "website": "www.mayanguides.com"}',
  'Mexico',
  now() - interval '3 years',
  now()
),
(
  'demo-ahmed-id',
  'demo-ahmed-user',
  'ahmed@demoguides.com',
  'Ahmed Hassan',
  'content_creator',
  'verified',
  true,
  'Cairo-born historian and storyteller who brings ancient Egypt to life. Expert in hieroglyphics, pyramid construction, and pharaonic dynasties with engaging storytelling.',
  ARRAY['Ancient Egypt', 'Hieroglyphics', 'Pyramids', 'Islamic Architecture'],
  ARRAY['English', 'Arabic'],
  12,
  'gold',
  950,
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
  '{"youtube": "AhmedEgyptExplorer", "instagram": "@cairo_stories"}',
  'Egypt',
  now() - interval '2.5 years',
  now()
);

-- Insert demo traveler profiles
INSERT INTO public.profiles (
  id, user_id, email, full_name, role, verification_status, 
  bio, specialties, languages_spoken, experience_years, current_tier, tier_points,
  avatar_url, created_at, updated_at
) VALUES 
(
  'demo-alex-id',
  'demo-alex-user',
  'alex@demousers.com',
  'Alex Thompson',
  'traveler',
  'unverified',
  'Travel enthusiast who loves discovering hidden gems and local cultures around the world. Always looking for authentic experiences and local guides.',
  ARRAY['Cultural Tourism', 'Photography', 'Local Cuisine'],
  ARRAY['English'],
  NULL,
  'bronze',
  120,
  'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400&h=400&fit=crop&crop=face',
  now() - interval '8 months',
  now()
),
(
  'demo-sarah-id',
  'demo-sarah-user',
  'sarah@demousers.com',
  'Sarah Williams',
  'traveler',
  'unverified',
  'Art lover and museum enthusiast. I enjoy guided tours that help me understand the deeper stories behind artworks and historical sites.',
  ARRAY['Art', 'Museums', 'History'],
  ARRAY['English', 'French'],
  NULL,
  'silver',
  280,
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
  now() - interval '1 year',
  now()
),
(
  'demo-david-id',
  'demo-david-user',
  'david@demousers.com',
  'David Chen',
  'traveler',
  'unverified',
  'Digital nomad exploring the world one city at a time. Passionate about architecture, local food scenes, and connecting with local experts.',
  ARRAY['Architecture', 'Food Tourism', 'Urban Exploration'],
  ARRAY['English', 'Mandarin'],
  NULL,
  'silver',
  340,
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
  now() - interval '6 months',
  now()
);