// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsaqlgxajdnwoqvtsrqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzYXFsZ3hhamRud29xdnRzcnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTA0MzgsImV4cCI6MjA3Mjc2NjQzOH0.qTVG_v_NqqX-vi7PDuf8p9qu_6pD5xKNhiPksqwJuzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    // Enhanced timeout and retry configuration for better regional connectivity
    fetch: (url, options: RequestInit = {}) => {
      const controller = new AbortController();
      // Increased timeout for regional users
      const timeoutId = setTimeout(() => controller.abort(), 60000); // 60 second timeout
      
      return fetch(url, {
        ...options,
        signal: controller.signal,
        // Add cache control for better regional performance
        headers: {
          // Properly handle Headers object or plain object
          ...(options.headers instanceof Headers 
            ? Object.fromEntries(options.headers.entries()) 
            : (options.headers || {})),
          'Cache-Control': 'public, max-age=300', // 5 minute cache
        },
      }).finally(() => {
        clearTimeout(timeoutId);
      });
    },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 2, // Reduce for better stability in poor connections
    },
  },
});